### ISSUE TITLE
finetune lr parameter overwritten on resuming (last fix seems insufficient)

### ISSUE THREAD

**Issue by mdukaczewski** [naoto0804/pytorch-inpainting-with-partial-conv#11]
https://github.com/naoto0804/pytorch-inpainting-with-partial-conv/blob/0ef695a6009d5080ecb50034795c9f28a758ab0f/train.py#L101

When you want to resume your model for finetuning, you overwritting new optimizer with the old one, and smaller lr is not applied. You would need something like this:
```
    for param_group in optimizer.param_groups:
        param_group['lr'] = lr
```

btw. finetuning with bn=False and smaller lr is giving nice results in my experiments with similar UNet architecture. I would suggest you to try it, if you didn't do that yet.

**Comment by naoto0804** [comment]
Fixed in #13, thank you!
I'm gonna update the results with the fine-tuned ones.
