### ISSUE TITLE
How to load Places2 dataset？

### ISSUE THREAD

**Issue by wangcx2018** [naoto0804/pytorch-inpainting-with-partial-conv#15]
How to access the Places2 datasets in this code? Should I download or not? If download in advance, where does it need to place? thanks!

**Comment by naoto0804** [comment]
@wangcx2018 It's pretty sophisticated and huge dataset developed by the following [paper](http://places2.csail.mit.edu/PAMI_places.pdf). On downloading, please follow the instructions on their website.
I expect to have `data_large`, `val_large`, and `test_large` under the root directory of Places2.
Specify the path of the Places2 dataset using an argument `--root /path/to/Places2` in `train.py`

**Comment by wangcx2018** [comment]
Thank you!
