### ISSUE TITLE
why change mask before output computation?

### ISSUE THREAD

**Issue by joemathai** [naoto0804/pytorch-inpainting-with-partial-conv#16]
hi,
Thanks for the implementation. I want to know why you have decided to do this https://github.com/naoto0804/pytorch-inpainting-with-partial-conv/blob/76ba1ee8e5588cbb2f1396b1a71daa64886537f6/net.py#L85 in your implementation when the original implementation details don't mention it.
http://masc.cs.gmu.edu/wiki/partialconv

**Comment by naoto0804** [comment]
Thank you for visiting this repository!
This is to assign pseudo value where `output_mask == 0`. Actually, the value `1.0` can be any value `a` except 0.0. Without that, zero division error will raise at the pixel where `mask_sum == 0` in https://github.com/naoto0804/pytorch-inpainting-with-partial-conv/blob/76ba1ee8e5588cbb2f1396b1a71daa64886537f6/net.py#L87
After that, we replace `a` with 0.0 again to keep correct value in https://github.com/naoto0804/pytorch-inpainting-with-partial-conv/blob/76ba1ee8e5588cbb2f1396b1a71daa64886537f6/net.py#L91

**Comment by joemathai** [comment]
Thanks for the clarification.
