### ISSUE TITLE
can it be used for arbitrary inpaiting(including random positions and shapes)?

### ISSUE THREAD

**Issue by micklexqg** [naoto0804/pytorch-inpainting-with-partial-conv#18]
hi, thanks for your work.
as the title, can it be used for arbitrary inpaiting(including random positions and shapes)?

**Comment by naoto0804** [comment]
According to the original [paper](https://arxiv.org/abs/1804.07723), it is possible.
If you come up with the specific patterns of the masks, please modify `generate_data.py`.

**Comment by jeejeelee** [comment]
@micklexqg  ,According to my experiment, it can inpaint any shapes and random positions if you generate random mask as many as possible .
