### ISSUE TITLE
The question about the size of the mask

### ISSUE THREAD

**Issue by quelladai** [naoto0804/pytorch-inpainting-with-partial-conv#2]
I am sorry to trouble you. I cannot understand the size of the mask and the feature here (https://github.com/naoto0804/pytorch-inpainting-with-partial-conv/blob/master/net.py#L74). The size of the mask here is 1? The size of the feature here is as the same as kernel or 1? Is the result of the formula here the result of every pixel? 
Thank you very much!

**Comment by naoto0804** [comment]
I think [this page](http://masc.cs.gmu.edu/wiki/partialconv) provided the authors is helpful.
Implementing the formula directly is not computationally efficient, so the authors suggested to implement it using off-the-shelf convolution operation for parallelization.
