### ISSUE TITLE
about the requirment.txt

### ISSUE THREAD

**Issue by NerminSalem** [naoto0804/pytorch-inpainting-with-partial-conv#21]
thanks for sharing your work
whenever i run  pip install -r requirements.txt, i got the following error:

 Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 3))
can u help? thanks

**Comment by naoto0804** [comment]
Thank you for reporting! Please remove that line.

**Comment by NerminSalem** [comment]
@naoto0804 that fixs it thanks alot for yr help
