### ISSUE TITLE
Pytorch version issue & Pretrained weight

### ISSUE THREAD

**Issue by shwoo1219** [naoto0804/pytorch-inpainting-with-partial-conv#22]
Hello, 

First of all, thanks for sharing your code.

I have several issues regarding to pytorch version and pretrained weight sharing request.

Due to dependency problem of another code, I am using now pytorch 0.4.0 version not 0.4.1 which is noted as a required version for this repo.

However, I found that by replacing F.interpolate function with F.upsample function makes everything fine. Is it okay to use this repo as this way?

Moreover, could you please share your pretrained weight ?

Looking forward to your reply.

Thanks.

**Comment by naoto0804** [comment]
Using `F.interpolate` will be OK if the actual operation is doing nearest-neigbour sampling, be careful.
[Here](https://www.dropbox.com/s/34ygasw6f7dt77p/1000000.pth?dl=0) is the pre-trained weight, but I cannot guarantee the quality. If you find any bugs, please report them!

**Comment by sunjunlishi** [comment]
it could be not reachead？

**Comment by naoto0804** [comment]
It's too large to be shown in the browser, but you can download it, don't you?

**Comment by sunjunlishi** [comment]
i have downloaded.My project is in need of watermarking and recognition

**Comment by peachis** [comment]
It seems like the link of the pre-train model you shared is unreachable. Would you please renew it.

Thanks a lot!

**Comment by naoto0804** [comment]
I have updated [here](https://drive.google.com/open?id=1G05AJjneRfdmBDaG4HlGCR8ZGxO7wizA)

**Comment by peachis** [comment]
Got it!
I have just tested it on Places2, and it works well.

Thank you again!
