### ISSUE TITLE
Is the test.py script wrong?

### ISSUE THREAD

**Issue by micklexqg** [naoto0804/pytorch-inpainting-with-partial-conv#24]
Should I have to provide the corresponding mask when testing?
i find no mask dataset root in the test.py, .
in the test.py:
dataset_val = Places2(args.root, img_transform, mask_transform, 'val')   (no mask root)
in the train.py:
dataset_val = Places2(args.root, args.mask_root, img_tf, mask_tf, 'val')   (with mask root)
so, how to implement 'test' exactly?

**Comment by naoto0804** [comment]
Please see #14. You might prepare some masks and train/val/test splits that meets your requirement.
