### ISSUE TITLE
regarding updating the mask step

### ISSUE THREAD

**Issue by NerminSalem** [naoto0804/pytorch-inpainting-with-partial-conv#25]
thanks for sharing yr work
i have a question regarding how do u update the mask? i really don't get it from paper
your help is really appreciated

**Comment by naoto0804** [comment]
In addition to the original paper, [this page](http://masc.cs.gmu.edu/wiki/partialconv) by the authors was really helpful to me.

**Comment by NerminSalem** [comment]
thanks i will check it out
