### ISSUE TITLE
about CUDA_VISIBLE_DEVICES id

### ISSUE THREAD

**Issue by NerminSalem** [naoto0804/pytorch-inpainting-with-partial-conv#26]
sorry for asking many questions, i tried to train the network but i got the following error
![screenshot from 2018-10-25 23-28-43](https://user-images.githubusercontent.com/26221951/47531380-befd1900-d8ad-11e8-9009-12b0b8319489.png)
@naoto0804 yr help is really appreciated

**Comment by NerminSalem** [comment]
@naoto0804 can the code works with single GPU?

**Comment by naoto0804** [comment]
It's not the single/multi-GPU problem. This is because `num_samples == 0` in InfiniteSampler. Please check if the dataset is correctly initialized using Places2 dataset.  Maybe you run the code although `len(dataset_train) == 0`.

**Comment by NerminSalem** [comment]
Thanks i will check it
