### ISSUE TITLE
there is a patch in image corner when training?

### ISSUE THREAD

**Issue by xadxxadx** [naoto0804/pytorch-inpainting-with-partial-conv#31]
I train my images, and I find that there is a  patch like a QR code pattern on image corner
Sometimes disappear when image is not complex.  And not always on the same location but on 4 corner.
![image](https://user-images.githubusercontent.com/20379969/60581241-092d8700-9db9-11e9-99ad-86b0d7511c13.png)
![image](https://user-images.githubusercontent.com/20379969/60581272-15b1df80-9db9-11e9-8e0c-ec408a011772.png)

**Comment by naoto0804** [comment]
At the corners, some of the information from the lower layer is masked. Thus, it is natural that the estimation on corners maybe sometimes unstable. However, there might be some bug in my implementation. Let me know if you have found something.
