### ISSUE TITLE
can I just run test.py without dowload Places2 dataset?

### ISSUE THREAD

**Issue by jobsfan** [naoto0804/pytorch-inpainting-with-partial-conv#33]
Can I just download the trained model file and won't download the dataset? The dataset is really too big!! I just wanna to test the result(some pictures I found from interet for random for testing), can it work?

I downloaded the **1000000.pth** file your trained and placed it in ./snapshots/default/1000000.pth
then I change the test.py to **parser.add_argument('--snapshot', type=str, default='./snapshots/default/1000000.pth')**

I made a folder structure like(**without any pictures or dataset**):
![error3](https://user-images.githubusercontent.com/3395025/62102987-9fc46980-b2cd-11e9-93f1-1a00d1da927c.jpg)

also I run **generate_data.py** and got the following:
![error4](https://user-images.githubusercontent.com/3395025/62103076-f2058a80-b2cd-11e9-9761-b6b1227a0eee.jpg)

then I run "python test.py", and got errors as follow:
![error1](https://user-images.githubusercontent.com/3395025/62102587-16f8fe00-b2cc-11e9-8d36-3a537e703e58.jpg)

And I also found the same problem as https://github.com/naoto0804/pytorch-inpainting-with-partial-conv/issues/24. The number params input is not match.

in test.py, use it like **dataset_val = Places2(args.root, img_transform, mask_transform, 'val')**
and in places2.py, 

![error2](https://user-images.githubusercontent.com/3395025/62102935-5ecc5500-b2cd-11e9-810e-4ef20be518a8.jpg)

Can you pls let me kown wether there is a way just to test the model with some random pictures downloaded from internet?

**Comment by greysou1** [comment]
@jobsfan Did you figure it out?

**Comment by jiunyen-ching** [comment]
@Prudvi01 
in test.py, add
`parser.add_argument('--mask_root', type=str, default='/path/to/your/mask')`
and
`dataset_val = Places2(args.root, args.mask_root, img_transform, mask_transform, 'val')`

alternatively, add the path to your mask directory as such
`dataset_val = Places2(args.root, </path/to/your/mask>, img_transform, mask_transform, 'val')`
