### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by PaperKites** [naoto0804/pytorch-inpainting-with-partial-conv#36]
Is the pre-trained model trained on the Places2 or ImageNet dataset?

Because in the net.py file, a pre-trained model is called (vgg16) and it's trained on ImageNet.
https://github.com/naoto0804/pytorch-inpainting-with-partial-conv/blob/e04c84d2bfc2ef8b40ba4af13b08ea43c6057ea8/net.py#L35
And there is a python file called Places2.py, so I'm not sure on which dataset is the 100000.pth trained on.

Thank you for your time.

**Comment by naoto0804** [comment]
Since the model is from torchvision, it is pre-trained one ImageNet. Please make sure to visit docs of [torchvision.models](https://pytorch.org/docs/stable/torchvision/models.html).

**Comment by PaperKites** [comment]
So for the 10000.pth model, did you train it on the Places2 dataset? Because if so, it might be the cause of the artifacts (patches) that happen in the image corners. Because ImageNet has a different image size (resolution) than places2 dataset

PS: I'm not an expert, but I thought that might help ^^

**Comment by naoto0804** [comment]
I guess all the images are resized to a fixed resolution, regardless of the dataset used for training.
