### ISSUE TITLE
How to test this code on my own dataset?

### ISSUE THREAD

**Issue by fu123456** [naoto0804/pytorch-inpainting-with-partial-conv#41]
Hi, I want to know how to use this code to test on my own dataset? I try to run the following code "python test.py --snapshot ./1000000.pth --root ./dataset", where "./dataset" is my own dataset (*.jpg). But it outputs the error:
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    dataset_val = Places2(args.root, img_transform, mask_transform, 'val')
  File "/home/user/FG/code/pytorch-inpainting-with-partial-conv/places2.py", line 21, in __init__
    self.mask_paths = glob('{:s}/*.jpg'.format(mask_root))
TypeError: unsupported format string passed to Compose.__format__

How to solve this. Very thank you.

**Comment by fu123456** [comment]
In test.py, there is no any parameter about mask_root?

**Comment by naoto0804** [comment]
As a dataset for both training/testing, `Places2` class is used.
Please modify `Places2` class in `places2.py` to adapt your dataset.

**Comment by fu123456** [comment]
Thx. I only want to test on my images using the pre-trained model. For example, I have some images and their corresponding masks, then how to modify places.py to their results? Now, I have "dataset/my_test_256/*.jpg"  (input rgb images) and "dataset/my_mask_256/.*jpg" (the masks of input rgb images). Then  I try to run "python test.py --snapshot ./1000000.pth --root dataset", and it does not work. I cannot fine any parameter specifying the mask directory. So help me. Very thank you.

**Comment by fu123456** [comment]
@naoto0804 In other words, if I have a random image (my own) and its mask where I want to repair, then how to use this code to repair the missing region of the input image? Note that this input random image is considered as ground truth.

**Comment by naoto0804** [comment]
It's hard to help, just saying ` it does not work` is not informative to me. Again, you should edit whole `places2.py` since it is designed for the structure of Places2 dataset
