### ISSUE TITLE
Inquiry about LICENSE

### ISSUE THREAD

**Issue by ryosukenakamotorist** [naoto0804/pytorch-inpainting-with-partial-conv#49]
I would like to know the License about `pytorch-inpainting-with-partial-conv`.
Will it be MIT LICENSE such as other your repository, or if there is any restriction, I would like to know for using this code.

Thank you for your great job.

**Comment by naoto0804** [comment]
I've added the license file. Please make sure there are more recent papers whose codes are available.
https://github.com/naoto0804/pytorch-inpainting-with-partial-conv/commit/2e7f944cd0a0f8945d5675a78956b296e203e484

**Comment by ryosukenakamotorist** [comment]
Thank you for your quick reply!
