### ISSUE TITLE
bad examples

### ISSUE THREAD

**Issue by tengshaofeng** [naoto0804/pytorch-inpainting-with-partial-conv#53]
@naoto0804 hi， so appreciate with your great work. When I test my image with your pretrained model，it coms bad result:
![image](https://user-images.githubusercontent.com/9246739/110104656-64abe580-7de2-11eb-8e4f-fa2db4bf8a46.png)
![image](https://user-images.githubusercontent.com/9246739/110104684-6fff1100-7de2-11eb-8d16-2a9aab9eebf9.png)
![image](https://user-images.githubusercontent.com/9246739/110104751-860cd180-7de2-11eb-82c6-70eb95bbeb50.png)
![image](https://user-images.githubusercontent.com/9246739/110104870-a89eea80-7de2-11eb-959a-e33d4c4347e1.png)
![image](https://user-images.githubusercontent.com/9246739/110104924-b94f6080-7de2-11eb-9329-5d30633939a4.png)
how about yours result? can you help me?

**Comment by naoto0804** [comment]
The quality of removal depends on the dataset that your model is trained. Since the model provided is trained on Places2, it may not work in out-of-distribution data such as Faces.
