### ISSUE TITLE
版本不匹配

### ISSUE THREAD

**Issue by 01SHENyankun** [naoto0804/pytorch-inpainting-with-partial-conv#58]
![6BM03@IL3@DVT_MYZD)ZVKL](https://user-images.githubusercontent.com/84694608/163668322-76907eb0-8ed7-48c7-a4a4-f50b05c1fd2c.png)

My torch is 0.4.1, CUDA is 9.0 and Python is 3.7, but I have encountered the above problems. Please give me some advice

**Comment by naoto0804** [comment]
I'm sorry but this seems to be a common issue using PyTorch. Someone may find the solution in the Web.
At least, please check if cuda is actually available from the program by `torch.cuda.is_available()`.
I guess the issue might be the [version mismatch](https://github.com/pytorch/pytorch/issues/17334), but not sure.
