### ISSUE TITLE
http://places2.csail.mit.edu/ が開けません

### ISSUE THREAD

**Issue by Yumekawa-chan** [naoto0804/pytorch-inpainting-with-partial-conv#63]
URLは正しいですか？

**Comment by naoto0804** [comment]
理由は不明ですが，アクセス不可能になっていますね; 調べてみるとkaggleにホストされているもの [link](https://www.kaggle.com/datasets/nickj26/places2-mit-dataset) などはまだヒットするので，それををあたってみても良いかもしれません
