### ISSUE TITLE
Do you have to provide the corresponding mask when testing?

### ISSUE THREAD

**Issue by SunHu1** [naoto0804/pytorch-inpainting-with-partial-conv#8]
I watched the introduction video，it can generate pictures based on different parts wiped by the user.

**Comment by naoto0804** [comment]
Note that this is an unofficial implementation (not the implementation by the authors of the papers).
Yes, it might be possible like [this](https://github.com/akmtn/pytorch-siggraph2017-inpainting). Contributions are welcome!
